/* automatically generated by rust-bindgen 0.60.1 */

#![allow(dead_code, non_camel_case_types, non_upper_case_globals, non_snake_case)]
use crate::channel::*;
use crate::config::tll_config_t;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tll_processor_loop_t {
    _unused: [u8; 0],
}
extern "C" {
    pub fn tll_processor_loop_new(
        name: *const ::std::os::raw::c_char,
        len: ::std::os::raw::c_int,
    ) -> *mut tll_processor_loop_t;
}
extern "C" {
    pub fn tll_processor_loop_new_cfg(cfg: *const tll_config_t) -> *mut tll_processor_loop_t;
}
extern "C" {
    pub fn tll_processor_loop_free(arg1: *mut tll_processor_loop_t);
}
extern "C" {
    pub fn tll_processor_loop_add(arg1: *mut tll_processor_loop_t, arg2: *mut tll_channel_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_del(arg1: *mut tll_processor_loop_t, arg2: *const tll_channel_t)
        -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_poll(
        arg1: *mut tll_processor_loop_t,
        timeout: ::std::os::raw::c_long,
    ) -> *mut tll_channel_t;
}
extern "C" {
    pub fn tll_processor_loop_process(arg1: *mut tll_processor_loop_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_pending(arg1: *mut tll_processor_loop_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_get_fd(arg1: *const tll_processor_loop_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_stop_get(arg1: *const tll_processor_loop_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_stop_set(
        arg1: *mut tll_processor_loop_t,
        flag: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_run(
        arg1: *mut tll_processor_loop_t,
        timeout: ::std::os::raw::c_long,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_run_signal(
        arg1: *mut tll_processor_loop_t,
        timeout: ::std::os::raw::c_long,
        signals: *const ::std::os::raw::c_int,
        sigsize: usize,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_loop_step(
        arg1: *mut tll_processor_loop_t,
        timeout: ::std::os::raw::c_long,
    ) -> ::std::os::raw::c_int;
}
