/* automatically generated by rust-bindgen 0.59.1 */

#![allow(dead_code, non_camel_case_types, non_upper_case_globals, non_snake_case)]
use crate::channel::*;
use crate::processor_loop::*;

pub type tll_processor_worker_t = tll_channel_t;
pub type tll_processor_t = tll_channel_t;
extern "C" {
    pub fn tll_processor_init(cctx: *mut tll_channel_context_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tll_processor_workers(p: *mut tll_processor_t) -> *mut tll_channel_list_t;
}
extern "C" {
    pub fn tll_processor_loop(p: *mut tll_processor_t) -> *mut tll_processor_loop_t;
}
extern "C" {
    pub fn tll_processor_worker_loop(w: *mut tll_processor_worker_t) -> *mut tll_processor_loop_t;
}
